<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/order.proto

namespace Vrp\Order;

use UnexpectedValueException;

/**
 * Protobuf type <code>vrp.Order.PriceMode</code>
 */
class PriceMode
{
    /**
     * Generated from protobuf enum <code>DEFAULT = 0;</code>
     */
    const PBDEFAULT = 0;
    /**
     * Generated from protobuf enum <code>FIXED_DECIMALS = 1;</code>
     */
    const FIXED_DECIMALS = 1;
    /**
     * Generated from protobuf enum <code>ASSET_DECIMALS = 2;</code>
     */
    const ASSET_DECIMALS = 2;

    private static $valueToName = [
        self::PBDEFAULT => 'PBDEFAULT',
        self::FIXED_DECIMALS => 'FIXED_DECIMALS',
        self::ASSET_DECIMALS => 'ASSET_DECIMALS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PriceMode::class, \Vrp\Order_PriceMode::class);

