# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/block.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vrp import transaction_pb2 as vrp_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvrp/block.proto\x12\x03vrp\x1a\x15vrp/transaction.proto\"\xe3\x02\n\x05\x42lock\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.vrp.Block.Header\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12,\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x16.vrp.SignedTransaction\x1a\xf5\x01\n\x06Header\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\x05\x12\x11\n\treference\x18\x02 \x01(\x0c\x12\x13\n\x0b\x62\x61se_target\x18\x03 \x01(\x03\x12\x1c\n\x14generation_signature\x18\x04 \x01(\x0c\x12\x15\n\rfeature_votes\x18\x05 \x03(\r\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x0f\n\x07version\x18\x07 \x01(\x05\x12\x11\n\tgenerator\x18\x08 \x01(\x0c\x12\x13\n\x0breward_vote\x18\t \x01(\x03\x12\x15\n\rreward_burned\x18\n \x01(\x03\x12\x19\n\x11transactions_root\x18\x0b \x01(\x0c\"\x9a\x01\n\nMicroBlock\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\treference\x18\x02 \x01(\x0c\x12\x1f\n\x17updated_block_signature\x18\x03 \x01(\x0c\x12\x19\n\x11sender_public_key\x18\x04 \x01(\x0c\x12,\n\x0ctransactions\x18\x05 \x03(\x0b\x32\x16.vrp.SignedTransaction\"c\n\x10SignedMicroBlock\x12$\n\x0bmicro_block\x18\x01 \x01(\x0b\x32\x0f.vrp.MicroBlock\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x16\n\x0etotal_block_id\x18\x03 \x01(\x0c\x42R\n\x16\x63om.vrp.protobuf.blockZ2github.com/eVESTXCOIN/govrp/pkg/grpc/generated/vrp\xaa\x02\x03VRPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vrp.block_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.vrp.protobuf.blockZ2github.com/eVESTXCOIN/govrp/pkg/grpc/generated/vrp\252\002\003VRP'
  _BLOCK._serialized_start=48
  _BLOCK._serialized_end=403
  _BLOCK_HEADER._serialized_start=158
  _BLOCK_HEADER._serialized_end=403
  _MICROBLOCK._serialized_start=406
  _MICROBLOCK._serialized_end=560
  _SIGNEDMICROBLOCK._serialized_start=562
  _SIGNEDMICROBLOCK._serialized_end=661
# @@protoc_insertion_point(module_scope)
