// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vrp/recipient.proto

package com.vrp.protobuf.transaction;

public final class RecipientOuterClass {
  private RecipientOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecipientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vrp.Recipient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * First 20 bytes of the result of the Keccak256(Blake2b256(publicKey)) hashing function.
     * </pre>
     *
     * <code>bytes public_key_hash = 1;</code>
     * @return The publicKeyHash.
     */
    com.google.protobuf.ByteString getPublicKeyHash();

    /**
     * <code>string alias = 2;</code>
     * @return The alias.
     */
    java.lang.String getAlias();
    /**
     * <code>string alias = 2;</code>
     * @return The bytes for alias.
     */
    com.google.protobuf.ByteString
        getAliasBytes();

    public com.vrp.protobuf.transaction.RecipientOuterClass.Recipient.RecipientCase getRecipientCase();
  }
  /**
   * Protobuf type {@code vrp.Recipient}
   */
  public static final class Recipient extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:vrp.Recipient)
      RecipientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Recipient.newBuilder() to construct.
    private Recipient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Recipient() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Recipient();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Recipient(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              recipientCase_ = 1;
              recipient_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              recipientCase_ = 2;
              recipient_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vrp.protobuf.transaction.RecipientOuterClass.internal_static_vrp_Recipient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vrp.protobuf.transaction.RecipientOuterClass.internal_static_vrp_Recipient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vrp.protobuf.transaction.RecipientOuterClass.Recipient.class, com.vrp.protobuf.transaction.RecipientOuterClass.Recipient.Builder.class);
    }

    private int recipientCase_ = 0;
    private java.lang.Object recipient_;
    public enum RecipientCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PUBLIC_KEY_HASH(1),
      ALIAS(2),
      RECIPIENT_NOT_SET(0);
      private final int value;
      private RecipientCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RecipientCase valueOf(int value) {
        return forNumber(value);
      }

      public static RecipientCase forNumber(int value) {
        switch (value) {
          case 1: return PUBLIC_KEY_HASH;
          case 2: return ALIAS;
          case 0: return RECIPIENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public RecipientCase
    getRecipientCase() {
      return RecipientCase.forNumber(
          recipientCase_);
    }

    public static final int PUBLIC_KEY_HASH_FIELD_NUMBER = 1;
    /**
     * <pre>
     * First 20 bytes of the result of the Keccak256(Blake2b256(publicKey)) hashing function.
     * </pre>
     *
     * <code>bytes public_key_hash = 1;</code>
     * @return The publicKeyHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKeyHash() {
      if (recipientCase_ == 1) {
        return (com.google.protobuf.ByteString) recipient_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int ALIAS_FIELD_NUMBER = 2;
    /**
     * <code>string alias = 2;</code>
     * @return The alias.
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = "";
      if (recipientCase_ == 2) {
        ref = recipient_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (recipientCase_ == 2) {
          recipient_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string alias = 2;</code>
     * @return The bytes for alias.
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = "";
      if (recipientCase_ == 2) {
        ref = recipient_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (recipientCase_ == 2) {
          recipient_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (recipientCase_ == 1) {
        output.writeBytes(
            1, (com.google.protobuf.ByteString) recipient_);
      }
      if (recipientCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, recipient_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (recipientCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              1, (com.google.protobuf.ByteString) recipient_);
      }
      if (recipientCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, recipient_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.vrp.protobuf.transaction.RecipientOuterClass.Recipient)) {
        return super.equals(obj);
      }
      com.vrp.protobuf.transaction.RecipientOuterClass.Recipient other = (com.vrp.protobuf.transaction.RecipientOuterClass.Recipient) obj;

      if (!getRecipientCase().equals(other.getRecipientCase())) return false;
      switch (recipientCase_) {
        case 1:
          if (!getPublicKeyHash()
              .equals(other.getPublicKeyHash())) return false;
          break;
        case 2:
          if (!getAlias()
              .equals(other.getAlias())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (recipientCase_) {
        case 1:
          hash = (37 * hash) + PUBLIC_KEY_HASH_FIELD_NUMBER;
          hash = (53 * hash) + getPublicKeyHash().hashCode();
          break;
        case 2:
          hash = (37 * hash) + ALIAS_FIELD_NUMBER;
          hash = (53 * hash) + getAlias().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.vrp.protobuf.transaction.RecipientOuterClass.Recipient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vrp.Recipient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vrp.Recipient)
        com.vrp.protobuf.transaction.RecipientOuterClass.RecipientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vrp.protobuf.transaction.RecipientOuterClass.internal_static_vrp_Recipient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vrp.protobuf.transaction.RecipientOuterClass.internal_static_vrp_Recipient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vrp.protobuf.transaction.RecipientOuterClass.Recipient.class, com.vrp.protobuf.transaction.RecipientOuterClass.Recipient.Builder.class);
      }

      // Construct using com.vrp.protobuf.transaction.RecipientOuterClass.Recipient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        recipientCase_ = 0;
        recipient_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vrp.protobuf.transaction.RecipientOuterClass.internal_static_vrp_Recipient_descriptor;
      }

      @java.lang.Override
      public com.vrp.protobuf.transaction.RecipientOuterClass.Recipient getDefaultInstanceForType() {
        return com.vrp.protobuf.transaction.RecipientOuterClass.Recipient.getDefaultInstance();
      }

      @java.lang.Override
      public com.vrp.protobuf.transaction.RecipientOuterClass.Recipient build() {
        com.vrp.protobuf.transaction.RecipientOuterClass.Recipient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.vrp.protobuf.transaction.RecipientOuterClass.Recipient buildPartial() {
        com.vrp.protobuf.transaction.RecipientOuterClass.Recipient result = new com.vrp.protobuf.transaction.RecipientOuterClass.Recipient(this);
        if (recipientCase_ == 1) {
          result.recipient_ = recipient_;
        }
        if (recipientCase_ == 2) {
          result.recipient_ = recipient_;
        }
        result.recipientCase_ = recipientCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vrp.protobuf.transaction.RecipientOuterClass.Recipient) {
          return mergeFrom((com.vrp.protobuf.transaction.RecipientOuterClass.Recipient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vrp.protobuf.transaction.RecipientOuterClass.Recipient other) {
        if (other == com.vrp.protobuf.transaction.RecipientOuterClass.Recipient.getDefaultInstance()) return this;
        switch (other.getRecipientCase()) {
          case PUBLIC_KEY_HASH: {
            setPublicKeyHash(other.getPublicKeyHash());
            break;
          }
          case ALIAS: {
            recipientCase_ = 2;
            recipient_ = other.recipient_;
            onChanged();
            break;
          }
          case RECIPIENT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vrp.protobuf.transaction.RecipientOuterClass.Recipient parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vrp.protobuf.transaction.RecipientOuterClass.Recipient) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int recipientCase_ = 0;
      private java.lang.Object recipient_;
      public RecipientCase
          getRecipientCase() {
        return RecipientCase.forNumber(
            recipientCase_);
      }

      public Builder clearRecipient() {
        recipientCase_ = 0;
        recipient_ = null;
        onChanged();
        return this;
      }


      /**
       * <pre>
       * First 20 bytes of the result of the Keccak256(Blake2b256(publicKey)) hashing function.
       * </pre>
       *
       * <code>bytes public_key_hash = 1;</code>
       * @return The publicKeyHash.
       */
      public com.google.protobuf.ByteString getPublicKeyHash() {
        if (recipientCase_ == 1) {
          return (com.google.protobuf.ByteString) recipient_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <pre>
       * First 20 bytes of the result of the Keccak256(Blake2b256(publicKey)) hashing function.
       * </pre>
       *
       * <code>bytes public_key_hash = 1;</code>
       * @param value The publicKeyHash to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKeyHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  recipientCase_ = 1;
        recipient_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * First 20 bytes of the result of the Keccak256(Blake2b256(publicKey)) hashing function.
       * </pre>
       *
       * <code>bytes public_key_hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKeyHash() {
        if (recipientCase_ == 1) {
          recipientCase_ = 0;
          recipient_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string alias = 2;</code>
       * @return The alias.
       */
      @java.lang.Override
      public java.lang.String getAlias() {
        java.lang.Object ref = "";
        if (recipientCase_ == 2) {
          ref = recipient_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (recipientCase_ == 2) {
            recipient_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string alias = 2;</code>
       * @return The bytes for alias.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAliasBytes() {
        java.lang.Object ref = "";
        if (recipientCase_ == 2) {
          ref = recipient_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (recipientCase_ == 2) {
            recipient_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string alias = 2;</code>
       * @param value The alias to set.
       * @return This builder for chaining.
       */
      public Builder setAlias(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  recipientCase_ = 2;
        recipient_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string alias = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlias() {
        if (recipientCase_ == 2) {
          recipientCase_ = 0;
          recipient_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string alias = 2;</code>
       * @param value The bytes for alias to set.
       * @return This builder for chaining.
       */
      public Builder setAliasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        recipientCase_ = 2;
        recipient_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:vrp.Recipient)
    }

    // @@protoc_insertion_point(class_scope:vrp.Recipient)
    private static final com.vrp.protobuf.transaction.RecipientOuterClass.Recipient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.vrp.protobuf.transaction.RecipientOuterClass.Recipient();
    }

    public static com.vrp.protobuf.transaction.RecipientOuterClass.Recipient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Recipient>
        PARSER = new com.google.protobuf.AbstractParser<Recipient>() {
      @java.lang.Override
      public Recipient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Recipient(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Recipient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Recipient> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.vrp.protobuf.transaction.RecipientOuterClass.Recipient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vrp_Recipient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vrp_Recipient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023vrp/recipient.proto\022\003vrp\"D\n\tRecipient\022" +
      "\031\n\017public_key_hash\030\001 \001(\014H\000\022\017\n\005alias\030\002 \001(" +
      "\tH\000B\013\n\trecipientBX\n\034com.vrp.protobuf.tra" +
      "nsactionZ2github.com/eVESTXCOIN/govrp/pk" +
      "g/grpc/generated/vrp\252\002\003VRPb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_vrp_Recipient_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vrp_Recipient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vrp_Recipient_descriptor,
        new java.lang.String[] { "PublicKeyHash", "Alias", "Recipient", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
