// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vrp/block.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Block_Header;
@class MicroBlock;
@class SignedTransaction;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BlockRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface BlockRoot : GPBRootObject
@end

#pragma mark - Block

typedef GPB_ENUM(Block_FieldNumber) {
  Block_FieldNumber_Header = 1,
  Block_FieldNumber_Signature = 2,
  Block_FieldNumber_TransactionsArray = 3,
};

GPB_FINAL @interface Block : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Block_Header *header;
/** Test to see if @c header has been set. */
@property(nonatomic, readwrite) BOOL hasHeader;

@property(nonatomic, readwrite, copy, null_resettable) NSData *signature;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SignedTransaction*> *transactionsArray;
/** The number of items in @c transactionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionsArray_Count;

@end

#pragma mark - Block_Header

typedef GPB_ENUM(Block_Header_FieldNumber) {
  Block_Header_FieldNumber_ChainId = 1,
  Block_Header_FieldNumber_Reference = 2,
  Block_Header_FieldNumber_BaseTarget = 3,
  Block_Header_FieldNumber_GenerationSignature = 4,
  Block_Header_FieldNumber_FeatureVotesArray = 5,
  Block_Header_FieldNumber_Timestamp = 6,
  Block_Header_FieldNumber_Version = 7,
  Block_Header_FieldNumber_Generator = 8,
  Block_Header_FieldNumber_RewardVote = 9,
  Block_Header_FieldNumber_RewardBurned = 10,
  Block_Header_FieldNumber_TransactionsRoot = 11,
};

GPB_FINAL @interface Block_Header : GPBMessage

@property(nonatomic, readwrite) int32_t chainId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *reference;

@property(nonatomic, readwrite) int64_t baseTarget;

@property(nonatomic, readwrite, copy, null_resettable) NSData *generationSignature;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *featureVotesArray;
/** The number of items in @c featureVotesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger featureVotesArray_Count;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite, copy, null_resettable) NSData *generator;

@property(nonatomic, readwrite) int64_t rewardVote;

@property(nonatomic, readwrite) int64_t rewardBurned;

@property(nonatomic, readwrite, copy, null_resettable) NSData *transactionsRoot;

@end

#pragma mark - MicroBlock

typedef GPB_ENUM(MicroBlock_FieldNumber) {
  MicroBlock_FieldNumber_Version = 1,
  MicroBlock_FieldNumber_Reference = 2,
  MicroBlock_FieldNumber_UpdatedBlockSignature = 3,
  MicroBlock_FieldNumber_SenderPublicKey = 4,
  MicroBlock_FieldNumber_TransactionsArray = 5,
};

GPB_FINAL @interface MicroBlock : GPBMessage

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite, copy, null_resettable) NSData *reference;

@property(nonatomic, readwrite, copy, null_resettable) NSData *updatedBlockSignature;

@property(nonatomic, readwrite, copy, null_resettable) NSData *senderPublicKey;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SignedTransaction*> *transactionsArray;
/** The number of items in @c transactionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionsArray_Count;

@end

#pragma mark - SignedMicroBlock

typedef GPB_ENUM(SignedMicroBlock_FieldNumber) {
  SignedMicroBlock_FieldNumber_MicroBlock = 1,
  SignedMicroBlock_FieldNumber_Signature = 2,
  SignedMicroBlock_FieldNumber_TotalBlockId = 3,
};

GPB_FINAL @interface SignedMicroBlock : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MicroBlock *microBlock;
/** Test to see if @c microBlock has been set. */
@property(nonatomic, readwrite) BOOL hasMicroBlock;

@property(nonatomic, readwrite, copy, null_resettable) NSData *signature;

@property(nonatomic, readwrite, copy, null_resettable) NSData *totalBlockId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
