<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/block.proto

namespace Vrp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>vrp.Block</code>
 */
class Block extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.vrp.Block.Header header = 1;</code>
     */
    protected $header = null;
    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>repeated .vrp.SignedTransaction transactions = 3;</code>
     */
    private $transactions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vrp\Block\Header $header
     *     @type string $signature
     *     @type \Vrp\SignedTransaction[]|\Google\Protobuf\Internal\RepeatedField $transactions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vrp\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.vrp.Block.Header header = 1;</code>
     * @return \Vrp\Block\Header
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.vrp.Block.Header header = 1;</code>
     * @param \Vrp\Block\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Vrp\Block_Header::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .vrp.SignedTransaction transactions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Generated from protobuf field <code>repeated .vrp.SignedTransaction transactions = 3;</code>
     * @param \Vrp\SignedTransaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Vrp\SignedTransaction::class);
        $this->transactions = $arr;

        return $this;
    }

}

