<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/transaction.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\DataTransactionData\DataEntry instead.
     * @deprecated
     */
    class DataTransactionData_DataEntry {}
}
class_exists(DataTransactionData\DataEntry::class);
@trigger_error('Vrp\DataTransactionData_DataEntry is deprecated and will be removed in the next major release. Use Vrp\DataTransactionData\DataEntry instead', E_USER_DEPRECATED);

