<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\LeaseCancel instead.
     * @deprecated
     */
    class InvokeScriptResult_LeaseCancel {}
}
class_exists(InvokeScriptResult\LeaseCancel::class);
@trigger_error('Vrp\InvokeScriptResult_LeaseCancel is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\LeaseCancel instead', E_USER_DEPRECATED);

