<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\Reissue instead.
     * @deprecated
     */
    class InvokeScriptResult_Reissue {}
}
class_exists(InvokeScriptResult\Reissue::class);
@trigger_error('Vrp\InvokeScriptResult_Reissue is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\Reissue instead', E_USER_DEPRECATED);

