<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\Burn instead.
     * @deprecated
     */
    class InvokeScriptResult_Burn {}
}
class_exists(InvokeScriptResult\Burn::class);
@trigger_error('Vrp\InvokeScriptResult_Burn is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\Burn instead', E_USER_DEPRECATED);

