<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\ErrorMessage instead.
     * @deprecated
     */
    class InvokeScriptResult_ErrorMessage {}
}
class_exists(InvokeScriptResult\ErrorMessage::class);
@trigger_error('Vrp\InvokeScriptResult_ErrorMessage is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\ErrorMessage instead', E_USER_DEPRECATED);

