<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\Issue instead.
     * @deprecated
     */
    class InvokeScriptResult_Issue {}
}
class_exists(InvokeScriptResult\Issue::class);
@trigger_error('Vrp\InvokeScriptResult_Issue is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\Issue instead', E_USER_DEPRECATED);

