<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\Invocation instead.
     * @deprecated
     */
    class InvokeScriptResult_Invocation {}
}
class_exists(InvokeScriptResult\Invocation::class);
@trigger_error('Vrp\InvokeScriptResult_Invocation is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\Invocation instead', E_USER_DEPRECATED);

