<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\Lease instead.
     * @deprecated
     */
    class InvokeScriptResult_Lease {}
}
class_exists(InvokeScriptResult\Lease::class);
@trigger_error('Vrp\InvokeScriptResult_Lease is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\Lease instead', E_USER_DEPRECATED);

