<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\Payment instead.
     * @deprecated
     */
    class InvokeScriptResult_Payment {}
}
class_exists(InvokeScriptResult\Payment::class);
@trigger_error('Vrp\InvokeScriptResult_Payment is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\Payment instead', E_USER_DEPRECATED);

