<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\PrivatePayment instead.
     * @deprecated
     */
    class InvokeScriptResult_PrivatePayment {}
}
class_exists(InvokeScriptResult\PrivatePayment::class);
@trigger_error('Vrp\InvokeScriptResult_PrivatePayment is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\PrivatePayment instead', E_USER_DEPRECATED);

