<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/invoke_script_result.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\InvokeScriptResult\Call\Argument\PBList instead.
     * @deprecated
     */
    class InvokeScriptResult_Call_Argument_List {}
}
class_exists(InvokeScriptResult\Call\Argument\PBList::class);
@trigger_error('Vrp\InvokeScriptResult_Call_Argument_List is deprecated and will be removed in the next major release. Use Vrp\InvokeScriptResult\Call\Argument\PBList instead', E_USER_DEPRECATED);

