<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/transaction.proto

namespace Vrp;

if (false) {
    /**
     * This class is deprecated. Use Vrp\MassTransferTransactionData\Transfer instead.
     * @deprecated
     */
    class MassTransferTransactionData_Transfer {}
}
class_exists(MassTransferTransactionData\Transfer::class);
@trigger_error('Vrp\MassTransferTransactionData_Transfer is deprecated and will be removed in the next major release. Use Vrp\MassTransferTransactionData\Transfer instead', E_USER_DEPRECATED);

