# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp/transaction.proto

require 'google/protobuf'

require 'vrp/amount_pb'
require 'vrp/recipient_pb'
require 'vrp/order_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vrp/transaction.proto", :syntax => :proto3) do
    add_message "vrp.SignedTransaction" do
      repeated :proofs, :bytes, 2
      oneof :transaction do
        optional :vrp_transaction, :message, 1, "vrp.Transaction"
        optional :ethereum_transaction, :bytes, 3
      end
    end
    add_message "vrp.Transaction" do
      optional :chain_id, :int32, 1
      optional :sender_public_key, :bytes, 2
      optional :fee, :message, 3, "vrp.Amount"
      optional :timestamp, :int64, 4
      optional :version, :int32, 5
      oneof :data do
        optional :genesis, :message, 101, "vrp.GenesisTransactionData"
        optional :payment, :message, 102, "vrp.PaymentTransactionData"
        optional :issue, :message, 103, "vrp.IssueTransactionData"
        optional :transfer, :message, 104, "vrp.TransferTransactionData"
        optional :reissue, :message, 105, "vrp.ReissueTransactionData"
        optional :burn, :message, 106, "vrp.BurnTransactionData"
        optional :exchange, :message, 107, "vrp.ExchangeTransactionData"
        optional :lease, :message, 108, "vrp.LeaseTransactionData"
        optional :lease_cancel, :message, 109, "vrp.LeaseCancelTransactionData"
        optional :create_alias, :message, 110, "vrp.CreateAliasTransactionData"
        optional :mass_transfer, :message, 111, "vrp.MassTransferTransactionData"
        optional :data_transaction, :message, 112, "vrp.DataTransactionData"
        optional :set_script, :message, 113, "vrp.SetScriptTransactionData"
        optional :sponsor_fee, :message, 114, "vrp.SponsorFeeTransactionData"
        optional :set_asset_script, :message, 115, "vrp.SetAssetScriptTransactionData"
        optional :invoke_script, :message, 116, "vrp.InvokeScriptTransactionData"
        optional :update_asset_info, :message, 117, "vrp.UpdateAssetInfoTransactionData"
        optional :anonymous_tx, :message, 118, "vrp.PrivatePaymentTransactionData"
      end
    end
    add_message "vrp.GenesisTransactionData" do
      optional :recipient_address, :bytes, 1
      optional :amount, :int64, 2
    end
    add_message "vrp.PaymentTransactionData" do
      optional :recipient_address, :bytes, 1
      optional :amount, :int64, 2
    end
    add_message "vrp.TransferTransactionData" do
      optional :recipient, :message, 1, "vrp.Recipient"
      optional :amount, :message, 2, "vrp.Amount"
      optional :attachment, :bytes, 3
    end
    add_message "vrp.CreateAliasTransactionData" do
      optional :alias, :string, 1
    end
    add_message "vrp.DataTransactionData" do
      repeated :data, :message, 1, "vrp.DataTransactionData.DataEntry"
    end
    add_message "vrp.DataTransactionData.DataEntry" do
      optional :key, :string, 1
      oneof :value do
        optional :int_value, :int64, 10
        optional :bool_value, :bool, 11
        optional :binary_value, :bytes, 12
        optional :string_value, :string, 13
      end
    end
    add_message "vrp.MassTransferTransactionData" do
      optional :asset_id, :bytes, 1
      repeated :transfers, :message, 2, "vrp.MassTransferTransactionData.Transfer"
      optional :attachment, :bytes, 3
    end
    add_message "vrp.MassTransferTransactionData.Transfer" do
      optional :recipient, :message, 1, "vrp.Recipient"
      optional :amount, :int64, 2
    end
    add_message "vrp.LeaseTransactionData" do
      optional :recipient, :message, 1, "vrp.Recipient"
      optional :amount, :int64, 2
    end
    add_message "vrp.LeaseCancelTransactionData" do
      optional :lease_id, :bytes, 1
    end
    add_message "vrp.BurnTransactionData" do
      optional :asset_amount, :message, 1, "vrp.Amount"
    end
    add_message "vrp.IssueTransactionData" do
      optional :name, :string, 1
      optional :description, :string, 2
      optional :amount, :int64, 3
      optional :decimals, :int32, 4
      optional :reissuable, :bool, 5
      optional :script, :bytes, 6
    end
    add_message "vrp.ReissueTransactionData" do
      optional :asset_amount, :message, 1, "vrp.Amount"
      optional :reissuable, :bool, 2
    end
    add_message "vrp.SetAssetScriptTransactionData" do
      optional :asset_id, :bytes, 1
      optional :script, :bytes, 2
    end
    add_message "vrp.SetScriptTransactionData" do
      optional :script, :bytes, 1
    end
    add_message "vrp.ExchangeTransactionData" do
      optional :amount, :int64, 1
      optional :price, :int64, 2
      optional :buy_matcher_fee, :int64, 3
      optional :sell_matcher_fee, :int64, 4
      repeated :orders, :message, 5, "vrp.Order"
    end
    add_message "vrp.SponsorFeeTransactionData" do
      optional :min_fee, :message, 1, "vrp.Amount"
    end
    add_message "vrp.InvokeScriptTransactionData" do
      optional :d_app, :message, 1, "vrp.Recipient"
      optional :function_call, :bytes, 2
      repeated :payments, :message, 3, "vrp.Amount"
    end
    add_message "vrp.UpdateAssetInfoTransactionData" do
      optional :asset_id, :bytes, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :image, :string, 4
    end
    add_message "vrp.InvokeExpressionTransactionData" do
      optional :expression, :bytes, 1
    end
    add_message "vrp.PrivatePaymentTransactionData" do
      optional :recipient_address, :bytes, 1
      optional :amount, :int64, 2
    end
  end
end

module Vrp
  SignedTransaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.SignedTransaction").msgclass
  Transaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.Transaction").msgclass
  GenesisTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.GenesisTransactionData").msgclass
  PaymentTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.PaymentTransactionData").msgclass
  TransferTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.TransferTransactionData").msgclass
  CreateAliasTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.CreateAliasTransactionData").msgclass
  DataTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.DataTransactionData").msgclass
  DataTransactionData::DataEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.DataTransactionData.DataEntry").msgclass
  MassTransferTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.MassTransferTransactionData").msgclass
  MassTransferTransactionData::Transfer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.MassTransferTransactionData.Transfer").msgclass
  LeaseTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.LeaseTransactionData").msgclass
  LeaseCancelTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.LeaseCancelTransactionData").msgclass
  BurnTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.BurnTransactionData").msgclass
  IssueTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.IssueTransactionData").msgclass
  ReissueTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.ReissueTransactionData").msgclass
  SetAssetScriptTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.SetAssetScriptTransactionData").msgclass
  SetScriptTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.SetScriptTransactionData").msgclass
  ExchangeTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.ExchangeTransactionData").msgclass
  SponsorFeeTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.SponsorFeeTransactionData").msgclass
  InvokeScriptTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.InvokeScriptTransactionData").msgclass
  UpdateAssetInfoTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.UpdateAssetInfoTransactionData").msgclass
  InvokeExpressionTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.InvokeExpressionTransactionData").msgclass
  PrivatePaymentTransactionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("vrp.PrivatePaymentTransactionData").msgclass
end
